{% set name = "formulas" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/vinci1it2000/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 49c5019d0609968ba76931c5fdb4e668bb105ffcd10ce3ca365a840e4041a424

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - ddt
    - docutils
    - flask
    - jinja2
    - multiprocess
    - nose
    - numpy >=1.15
    - openpyxl
    - pip
    - pygments
    - python >=3
    - python-graphviz
    - regex
    - requests
    - schedula >=1.1.1
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-restbuilder
  run:
    - numpy >=1.15
    - python >=3
    - python-dateutil
    - regex
    - schedula >=1.1.1

test:
  source_files:
    - setup.cfg
    - test
  requires:
    - ddt
    - dill
    - docutils
    - flask
    - jinja2
    - multiprocess
    - nose
    - numpy >=1.15
    - openpyxl
    - pip
    - pygments
    - python >=3
    - python-graphviz <0.10.1
    - regex
    - requests
    - schedula >=0.3.1
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-restbuilder
  imports:
    - formulas
  commands:
    - rm test/test_readme.py test/test_setup.py  # [unix]
    - del test\test_readme.py test\test_setup.py  # [win]
    - nosetests
    - python -m pip check

about:
  home: https://github.com/vinci1it2000/formulas
  license: EUPL-1.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Parse and compile Excel formulas and workbooks in python code.
  doc_url: https://formulas.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
