travis:
  secure:
    BINSTAR_TOKEN: FgmHIjVSD5yYia9HHzZFSZOlbTzjy47qkWFZFyixKVhcvG1qqgvl3DxYhrWMmErcEngffvylFy/asHOSDGWHgvDHcaUo6E9nHGYsDo3GS0QLHETwWip4rY9U3YO0KzbOafCqQGFOsVbysdsN3+Q6DqM6Hl35OcdpeniBqaRjB/7O2u940DIpoZbxOCkrymViCYf8e/0mStENJOfDyy7PnBX2omgfdKtkjNhJDEAyY6wbTvvC6zsBIXT+oCpjtVfBOF4owxkquj2G2E/6DUtKDMv3NTKBatjGaY7u3IVFiUnGSxaidUpOr6BXa61SID+dNozo8U2MwKKow5PYrWqALEbUaDuqqArbxJIUWWf8lDtiOqhO3Gn6KoEb/PszeAUlNW/xz/C7wbUfExrxSPSNjJxYcYcvMRemQ4DkRHHFiXo3sPNDWrtWyvS1c8GOdT5TS8fFV1UiIBWjsaYKeGq8Z+xnymhGVM3/CtfYPrgaynVuYyISdxbsgQ/jfON5DoJydS2J+dO/Ihl0WCtaUrSw6JxWtoZw7bpCB0qtWVN+BrV1lZhYQPzqbj+pcw/dHKb65SHWZkc4rT4QjWKUfkfrc80c26mo6Nr9PkKgPSf0kLOc2ZE85WPYLAAY26R2OGQLh9DQsCtHyL4IkBTwOp+jbcP6Lqcx0vK556zQb+VZPGk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
